### ISSUE TITLE
Run femtocleaner

### ISSUE THREAD

**Issue by matthewware** [BBN-Q/QuantumInfo.jl#2]
Attempt to trigger femtocleaner

**Comment by jlapeyre** [comment]
I forked and pushed a [branch](https://github.com/jlapeyre/QuantumInfo.jl/tree/upgradev1.0) that contains minimal edits for the test suite to pass without warnings on today's master branch of Julia. If you are interested, I'll make a PR.

**Comment by caryan** [comment]
Yes please!

**Comment by jlapeyre** [comment]
Good! I just pushed another branch that updates CI, test format, etc.

**Comment by matthewware** [comment]
Hi John!  Sure we'd love a PR.  I think Travis is currently failing on the 1.0 and nightly builds at the moment since versions > 0.7.x require the master branch of Cliffords.jl

**Comment by jlapeyre** [comment]
Yes it is failing. I'll try to get Travis to use the master branch of Cliffords.jl

**Comment by jlapeyre** [comment]
Finding the right incantation is a PITA, but Travis is now using the master branch of Cliffords.jl and the tests pass.

**Comment by matthewware** [comment]
I think we can close this issue now.
